# Site settings
name: Rohan Minocha
title: Rohan Minocha
description: student, developer, aspiring change-maker
url: https://rohanminochaa.github.io/
baseurl: ''
email: rminocha@uwaterloo.ca
cover: https://rohanminochaa.github.io/img/og.png
logo: https://rohanminochaa.github.io/img/emojis/fire.png
resume: https://rohanminochaa.github.io/resume.pdf
social:
  - title: email
    url: mailto:rminocha@uwaterloo.ca
  - title: github
    url: https://github.com/rohanminochaa
  - title: linkedin
    url: https://www.linkedin.com/in/rohanminocha

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
