# Site settings
name: Rohan Minocha
title: Rohan Minocha
description: student, developer, aspiring change-maker
url: https://rminocha.com/
baseurl: ""
email: rminocha@uwaterloo.ca
cover: https://rminocha.com/img/og.png
logo: https://rminocha.com/img/emojis/man_technologist.png
resume: https://rminocha.com/resume_external.pdf
social:
  - title: email
    url: mailto:rminocha@uwaterloo.ca
  - title: github
    url: https://github.com/rohanxminocha
  - title: linkedin
    url: https://www.linkedin.com/in/rohanminocha

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
